In [1]:
import pandas as pd
import covid_daily

from IPython.core.display import display, HTML 
display(HTML("<style>.container { width:100% !important; }</style>"))

df3 = covid_daily.covid_daily_report('04-12-2020')
df3.sort_values(by=['Deaths_per_1k'], ascending=False, inplace=True)
print(df3.columns)
display(df3.query("POPESTIMATE2019>100000").head(20))
display(df3.query("Admin2 in ['Rockland', 'Nassau', 'Blaine', 'Summit']").head(30))

Index(['STATE', 'COUNTY', 'POPESTIMATE2019', 'DEATHS2019', 'FIPS', 'Admin2',
       'Province_State', 'Confirmed', 'Deaths', 'TPOP_MORTALITY',
       'CASE_MORTALITY', 'TPOP_CONFIRMED', 'Cases_per_1k', 'Deaths_per_1k'],
      dtype='object')

,STATE,COUNTY,POPESTIMATE2019,DEATHS2019,FIPS,Admin2,Province_State,Confirmed,Deaths,TPOP_MORTALITY,CASE_MORTALITY,TPOP_CONFIRMED,Cases_per_1k,Deaths_per_1k
2658,36,61,8336817,62061,36061,New York City,New York,103208,6898,0.0827,6.6836,1.2380,12.38,0.83
1562,36,59,1356924,11312,36059,Nassau,New York,23553,846,0.0623,3.5919,1.7358,17.36,0.62
1573,36,87,325789,2457,36087,Rockland,New York,7721,200,0.0614,2.5903,2.3699,23.70,0.61
997,22,71,390144,3640,22071,Orleans,Louisiana,5600,235,0.0602,4.1964,1.4354,14.35,0.60
1493,34,13,798975,6457,34013,Essex,New Jersey,7410,428,0.0536,5.7760,0.9274,9.27,0.54
1589,36,119,967506,7582,36119,Westchester,New York,19313,511,0.0528,2.6459,1.9962,19.96,0.53
1488,34,3,932202,7248,34003,Bergen,New Jersey,9784,453,0.0486,4.6300,1.0496,10.50,0.49
1152,26,163,1749343,18385,26163,Wayne,Michigan,11164,704,0.0402,6.3060,0.6382,6.38,0.40
988,22,51,432493,4345,22051,Jefferson,Louisiana,4990,173,0.0400,3.4669,1.1538,11.54,0.40
1567,36,71,384940,2884,36071,Orange,New York,5027,145,0.0377,2.8844,1.3059,13.06,0.38
1506,34,39,556341,4195,34039,Union,New Jersey,6180,209,0.0376,3.3819,1.1108,11.11,0.38
1581,36,103,1476601,13146,36103,Suffolk,New York,20934,518,0.0351,2.4744,1.4177,14.18,0.35
1495,34,17,672391,4371,34017,Hudson,New Jersey,7469,226,0.0336,3.0258,1.1108,11.11,0.34
1500,34,27,491845,3857,34027,Morris,New Jersey,3099,162,0.0329,5.2275,0.6301,6.30,0.33
1133,26,125,1257584,10978,26125,Oakland,Michigan,4915,329,0.0262,6.6938,0.3908,3.91,0.26
1502,34,31,501826,3769,34031,Passaic,New Jersey,5590,131,0.0261,2.3435,1.1139,11.14,0.26
272,9,1,943332,6960,9001,Fairfield,Connecticut,5534,248,0.0263,4.4814,0.5866,5.87,0.26
1121,26,99,873972,8548,26099,Macomb,Michigan,3254,217,0.0248,6.6687,0.3723,3.72,0.25
1505,34,37,140488,1266,34037,Sussex,New Jersey,483,35,0.0249,7.2464,0.3438,3.44,0.25
1504,34,35,328934,2613,34035,Somerset,New Jersey,1732,79,0.0240,4.5612,0.5265,5.27,0.24

,STATE,COUNTY,POPESTIMATE2019,DEATHS2019,FIPS,Admin2,Province_State,Confirmed,Deaths,TPOP_MORTALITY,CASE_MORTALITY,TPOP_CONFIRMED,Cases_per_1k,Deaths_per_1k
1562,36,59,1356924,11312,36059,Nassau,New York,23553,846,0.0623,3.5919,1.7358,17.36,0.62
1573,36,87,325789,2457,36087,Rockland,New York,7721,200,0.0614,2.5903,2.3699,23.70,0.61
513,16,13,23021,106,16013,Blaine,Idaho,454,5,0.0217,1.1013,1.9721,19.72,0.22
267,8,117,31011,69,8117,Summit,Colorado,72,1,0.0032,1.3889,0.2322,2.32,0.03
1791,39,153,541013,5734,39153,Summit,Ohio,257,14,0.0026,5.4475,0.0475,0.48,0.03
2337,49,43,42145,159,49043,Summit,Utah,304,0,0.0000,0.0000,0.7213,7.21,0.00
328,12,89,88625,979,12089,Nassau,Florida,34,0,0.0000,0.0000,0.0384,0.38,0.00