In [6]:
import pandas as pd
import covid_daily

from IPython.core.display import display, HTML 
display(HTML("<style>.container { width:100% !important; }</style>"))

df3 = covid_daily.covid_daily_report('04-10-2020')

df3.sort_values(by=['Deaths_per_1k'], ascending=False, inplace=True)

df4 = df

display(df3.query("Deaths_per_1k>0").head(30))

,STATE,COUNTY,POPESTIMATE2019,DEATHS2019,FIPS,Admin2,Province_State,Confirmed,Deaths,TPOP_MORTALITY,CASE_MORTALITY,TPOP_CONFIRMED,Cases_per_1k,Deaths_per_1k
475,13,273,8531,115,13273,Terrell,Georgia,100,10,0.1172,10.0000,1.1722,11.72,1.17
988,22,95,42837,421,22095,St. John the Baptist,Louisiana,507,37,0.0864,7.2978,1.1836,11.84,0.86
393,13,95,87956,951,13095,Dougherty,Georgia,1062,67,0.0762,6.3089,1.2074,12.07,0.76
461,13,243,6778,71,13243,Randolph,Georgia,98,5,0.0738,5.1020,1.4459,14.46,0.74
2607,36,61,8336817,62061,36061,New York City,New York,92384,5820,0.0698,6.2998,1.1081,11.08,0.70
1783,40,55,5712,54,40055,Greer,Oklahoma,46,4,0.0700,8.6957,0.8053,8.05,0.70
350,13,7,3038,22,13007,Baker,Georgia,11,2,0.0658,18.1818,0.3621,3.62,0.66
1388,30,101,4736,44,30101,Toole,Montana,18,3,0.0633,16.6667,0.3801,3.80,0.63
1532,36,87,325789,2457,36087,Rockland,New York,7122,200,0.0614,2.8082,2.1861,21.86,0.61
443,13,205,21863,236,13205,Mitchell,Georgia,131,13,0.0595,9.9237,0.5992,5.99,0.59
976,22,71,390144,3640,22071,Orleans,Louisiana,5416,225,0.0577,4.1544,1.3882,13.88,0.58
1521,36,59,1356924,11312,36059,Nassau,New York,21512,723,0.0533,3.3609,1.5854,15.85,0.53
432,13,177,29992,245,13177,Lee,Georgia,222,15,0.0500,6.7568,0.7402,7.40,0.50
395,13,99,10190,142,13099,Early,Georgia,105,5,0.0491,4.7619,1.0304,10.30,0.49
2229,48,359,2112,12,48359,Oldham,Texas,3,1,0.0473,33.3333,0.1420,1.42,0.47
1455,34,13,798975,6457,34013,Essex,New Jersey,6580,352,0.0441,5.3495,0.8236,8.24,0.44
987,22,93,21096,226,22093,St. James,Louisiana,194,9,0.0427,4.6392,0.9196,9.20,0.43
985,22,89,53100,446,22089,St. Charles,Louisiana,376,23,0.0433,6.1170,0.7081,7.08,0.43
1450,34,3,932202,7248,34003,Bergen,New Jersey,8928,390,0.0418,4.3683,0.9577,9.58,0.42
1548,36,119,967506,7582,36119,Westchester,New York,18077,389,0.0402,2.1519,1.8684,18.68,0.40
967,22,51,432493,4345,22051,Jefferson,Louisiana,4678,165,0.0382,3.5271,1.0816,10.82,0.38
1128,26,163,1749343,18385,26163,Wayne,Michigan,10539,609,0.0348,5.7785,0.6025,6.02,0.35
376,13,61,2834,35,13061,Clay,Georgia,15,1,0.0353,6.6667,0.5293,5.29,0.35
1271,28,157,8630,122,28157,Wilkinson,Mississippi,40,3,0.0348,7.5000,0.4635,4.63,0.35
978,22,75,23197,195,22075,Plaquemines,Louisiana,130,8,0.0345,6.1538,0.5604,5.60,0.34
1000,22,121,26465,218,22121,West Baton Rouge,Louisiana,61,9,0.0340,14.7541,0.2305,2.30,0.34
365,13,37,6189,49,13037,Calhoun,Georgia,37,2,0.0323,5.4054,0.5978,5.98,0.32
642,18,47,22758,211,18047,Franklin,Indiana,66,7,0.0308,10.6061,0.2900,2.90,0.31
965,22,47,32511,313,22047,Iberville,Louisiana,198,10,0.0308,5.0505,0.6090,6.09,0.31
1652,38,29,3241,49,38029,Emmons,North Dakota,1,1,0.0309,100.0000,0.0309,0.31,0.31