In [23]:
import pandas as pd

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

def fips_glue(row):
    x = float(str(row['STATE']) + str(row['COUNTY']).zfill(3))
    return x

def pop_mortality(row):
    x = float("{:.4f}".format(row['Deaths'] / row['POPESTIMATE2019']* 100)) 
    return x

def case_mortality(row):
    if row['Confirmed'] == 0:
        return 0
    x = float("{:.4f}".format(row['Deaths'] / row['Confirmed']* 100)) 
    return x

def pop_confirmed(row):
    x = float("{:.4f}".format(row['Confirmed'] / row['POPESTIMATE2019']* 100)) 
    return x

cvd_data = pd.read_csv("../COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/04-05-2020.csv")
cvd_df = pd.DataFrame(cvd_data, columns = ['FIPS', 'Admin2', 'Province_State', 'Confirmed', 'Deaths'])


dem_data = pd.read_csv("./data/CO-EST2019-alldata.csv")
dem_df = pd.DataFrame(dem_data, columns = [ 'STATE', 'COUNTY', 'POPESTIMATE2019','DEATHS2019'])
dem_df['FIPS'] = dem_df.apply(fips_glue, axis = 1)

df3 = pd.merge(dem_df,cvd_df, on='FIPS')

df3['TPOP_MORTALITY'] = df3.apply(pop_mortality, axis = 1)
df3['CASE_MORTALITY'] = df3.apply(case_mortality, axis = 1)
df3['TPOP_CONFIRMED'] = df3.apply(pop_confirmed, axis = 1)

df3.sort_values(by=['Confirmed'], ascending=False, inplace=True)

display(df3.query("Deaths>20").head(20))

,STATE,COUNTY,POPESTIMATE2019,DEATHS2019,FIPS,Admin2,Province_State,Confirmed,Deaths,TPOP_MORTALITY,CASE_MORTALITY,TPOP_CONFIRMED
1430,36,61,1628706,12171,36061.0,New York City,New York,67551,2256,0.1385,3.3397,4.1475
1429,36,59,1356924,11312,36059.0,Nassau,New York,14398,162,0.0119,1.1252,1.0611
1457,36,119,967506,7582,36119.0,Westchester,New York,13723,67,0.0069,0.4882,1.4184
1449,36,103,1476601,13146,36103.0,Suffolk,New York,13129,175,0.0119,1.3329,0.8891
526,17,31,5150233,42432,17031.0,Cook,Illinois,8034,186,0.0036,2.3152,0.1560
1066,26,163,1749343,18385,26163.0,Wayne,Michigan,7518,293,0.0167,3.8973,0.4298
1359,34,3,932202,7248,34003.0,Bergen,New Jersey,6187,189,0.0203,3.0548,0.6637
169,6,37,10039107,68164,6037.0,Los Angeles,California,5955,132,0.0013,2.2166,0.0593
1441,36,87,325789,2457,36087.0,Rockland,New York,5326,69,0.0212,1.2955,1.6348
308,12,86,2716940,21689,12086.0,Miami-Dade,Florida,4146,31,0.0011,0.7477,0.1526
1364,34,13,798975,6457,34013.0,Essex,New Jersey,4082,172,0.0215,4.2136,0.5109
917,22,71,390144,3640,22071.0,Orleans,Louisiana,4066,161,0.0413,3.9597,1.0422
1366,34,17,672391,4371,34017.0,Hudson,New Jersey,3924,87,0.0129,2.2171,0.5836
1373,34,31,501826,3769,34031.0,Passaic,New Jersey,3227,42,0.0084,1.3015,0.6431
1377,34,39,556341,4195,34039.0,Union,New Jersey,3216,71,0.0128,2.2077,0.5781
1789,42,101,1584064,15561,42101.0,Philadelphia,Pennsylvania,3189,28,0.0018,0.8780,0.2013
1435,36,71,384940,2884,36071.0,Orange,New York,3187,53,0.0138,1.6630,0.8279
2308,53,33,2252782,13917,53033.0,King,Washington,3167,208,0.0092,6.5677,0.1406
908,22,51,432493,4345,22051.0,Jefferson,Louisiana,3088,113,0.0261,3.6593,0.7140
259,9,1,943332,6960,9001.0,Fairfield,Connecticut,3050,96,0.0102,3.1475,0.3233